name: backend-pr

# This workflow is triggered on pull requests to branch develop when changes happen in backend.
on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js 18.15.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install dependencies
        run: npm ci

      # - name: Run Tests
      #   run: npm run test:ci
